import Box from "@mui/material/Box";
import * as React from "react";
import styles from "../../styles/Home.module.css";
import Header from "../Header/Header";
import Head from "next/head";

export interface PageContainerProps {
  title: string;
}

export default function PageContainer({
  title,
  children,
}: React.PropsWithChildren<PageContainerProps>) {
  return (
    <Box className={styles.container}>
      <Head>
        <title>{title} - Partakefoods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Box margin={12}>
        @Empty footer
      </Box>
    </Box>
  );
}
