import type { NextPage } from "next";
import Head from "next/head";
import { ShoppingCart } from "../containers/ShoppingCart/ShoppingCart";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shopping Cart - Partakefoods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShoppingCart />
    </div>
  );
};

export default Home;
